user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

bory_de_saint_vincent:
    resource: "@BoryDeSaintVincentBundle/Controller/"
    type:     annotation
    prefix:   /
