<?php

namespace BorySaintVincentBundle\Repository;

use BorySaintVincentBundle\Entity\Absence;

/**
 * AbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Absence[]
     */
    public function findFromNow()
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder('a');

        return $queryBuilder
            ->select('a')
            ->from('BorySaintVincentBundle:Absence', 'a')
            ->where($queryBuilder->expr()->gte('a.startDate', ':now'))
            ->setParameter('now', \DateTime::createFromFormat('Y-m-d H:i:s', date('Y-m-d').' 00:00:00'))
            ->getQuery()
            ->getResult();
    }
}
